"""initial schema

Revision ID: 47ae70214128
Revises: 
Create Date: 2026-08-27 17:39:11.717352

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '47ae70214128'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('setting_type', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_settings_key'), 'application_settings', ['key'], unique=True)
    op.create_table('backups',
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('backup_type', sa.String(length=32), nullable=False),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('abbreviation', sa.String(length=32), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_table('commands',
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('command_text', sa.Text(), nullable=False),
    sa.Column('variables', sa.Text(), nullable=True),
    sa.Column('operating_system', sa.String(length=32), nullable=False),
    sa.Column('tool', sa.String(length=64), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commands_category'), 'commands', ['category'], unique=False)
    op.create_index(op.f('ix_commands_name'), 'commands', ['name'], unique=False)
    op.create_table('finding_templates',
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('cwe', sa.String(length=32), nullable=True),
    sa.Column('owasp_category', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('reproduction_guidance', sa.Text(), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('references', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finding_templates_title'), 'finding_templates', ['title'], unique=False)
    op.create_table('methodology_profiles',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_methodology_profiles_name'), 'methodology_profiles', ['name'], unique=True)
    op.create_table('payloads',
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=64), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('authorized_use_warning', sa.Text(), nullable=True),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payloads_category'), 'payloads', ['category'], unique=False)
    op.create_index(op.f('ix_payloads_name'), 'payloads', ['name'], unique=False)
    op.create_table('runner_nodes',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('architecture', sa.String(length=64), nullable=True),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('capabilities_json', sa.Text(), nullable=True),
    sa.Column('tools_json', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runner_nodes_name'), 'runner_nodes', ['name'], unique=False)
    op.create_table('tags',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('client_contacts',
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_contacts_client_id'), 'client_contacts', ['client_id'], unique=False)
    op.create_table('engagements',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('identifier', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('engagement_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('testing_window', sa.String(length=255), nullable=True),
    sa.Column('time_zone', sa.String(length=64), nullable=False),
    sa.Column('primary_tester', sa.String(length=128), nullable=True),
    sa.Column('scope_notes', sa.Text(), nullable=True),
    sa.Column('out_of_scope_notes', sa.Text(), nullable=True),
    sa.Column('rules_of_engagement', sa.Text(), nullable=True),
    sa.Column('emergency_contacts', sa.Text(), nullable=True),
    sa.Column('authorization_notes', sa.Text(), nullable=True),
    sa.Column('testing_constraints', sa.Text(), nullable=True),
    sa.Column('allowed_methods', sa.Text(), nullable=True),
    sa.Column('prohibited_methods', sa.Text(), nullable=True),
    sa.Column('data_handling', sa.Text(), nullable=True),
    sa.Column('reporting_requirements', sa.Text(), nullable=True),
    sa.Column('engagement_folder', sa.String(length=512), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_index(op.f('ix_engagements_client_id'), 'engagements', ['client_id'], unique=False)
    op.create_index(op.f('ix_engagements_name'), 'engagements', ['name'], unique=False)
    op.create_index(op.f('ix_engagements_status'), 'engagements', ['status'], unique=False)
    op.create_table('entity_tags',
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_tags_entity_id'), 'entity_tags', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_tags_entity_type'), 'entity_tags', ['entity_type'], unique=False)
    op.create_table('methodology_items',
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('guidance', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['methodology_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_methodology_items_profile_id'), 'methodology_items', ['profile_id'], unique=False)
    op.create_table('activity_events',
    sa.Column('engagement_id', sa.String(length=36), nullable=True),
    sa.Column('actor', sa.String(length=128), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=True),
    sa.Column('object_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_events_engagement_id'), 'activity_events', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_activity_events_event_type'), 'activity_events', ['event_type'], unique=False)
    op.create_table('attack_chains',
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity_uplift', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attack_chains_engagement_id'), 'attack_chains', ['engagement_id'], unique=False)
    op.create_table('attack_relationships',
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('relation', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('provenance', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attack_relationships_engagement_id'), 'attack_relationships', ['engagement_id'], unique=False)
    op.create_table('engagement_checklist_items',
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('checklist_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engagement_checklist_items_checklist_type'), 'engagement_checklist_items', ['checklist_type'], unique=False)
    op.create_index(op.f('ix_engagement_checklist_items_engagement_id'), 'engagement_checklist_items', ['engagement_id'], unique=False)
    op.create_table('engagement_members',
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engagement_members_engagement_id'), 'engagement_members', ['engagement_id'], unique=False)
    op.create_table('findings',
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('technical_details', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('cvss_version', sa.String(length=8), nullable=True),
    sa.Column('cvss_vector', sa.String(length=128), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('risk_rating', sa.String(length=32), nullable=True),
    sa.Column('cwe', sa.String(length=32), nullable=True),
    sa.Column('owasp_category', sa.String(length=128), nullable=True),
    sa.Column('mitre_technique', sa.String(length=128), nullable=True),
    sa.Column('nist_mapping', sa.Text(), nullable=True),
    sa.Column('cms_ars_mapping', sa.Text(), nullable=True),
    sa.Column('affected_endpoints', sa.Text(), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('likelihood', sa.String(length=32), nullable=True),
    sa.Column('business_impact', sa.Text(), nullable=True),
    sa.Column('reproduction_steps', sa.Text(), nullable=True),
    sa.Column('proof_of_concept', sa.Text(), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('references', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('assigned_tester', sa.String(length=128), nullable=True),
    sa.Column('client_owner', sa.String(length=128), nullable=True),
    sa.Column('date_discovered', sa.Date(), nullable=True),
    sa.Column('date_reported', sa.Date(), nullable=True),
    sa.Column('date_remediated', sa.Date(), nullable=True),
    sa.Column('retest_date', sa.Date(), nullable=True),
    sa.Column('retest_result', sa.String(length=64), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('client_visible_notes', sa.Text(), nullable=True),
    sa.Column('in_report', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_engagement_id'), 'findings', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_findings_severity'), 'findings', ['severity'], unique=False)
    op.create_index(op.f('ix_findings_status'), 'findings', ['status'], unique=False)
    op.create_index(op.f('ix_findings_title'), 'findings', ['title'], unique=False)
    op.create_table('link_collections',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('engagement_id', sa.String(length=36), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('report_format', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_engagement_id'), 'reports', ['engagement_id'], unique=False)
    op.create_table('scan_imports',
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('scan_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('imported_targets', sa.Integer(), nullable=False),
    sa.Column('imported_findings', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_imports_engagement_id'), 'scan_imports', ['engagement_id'], unique=False)
    op.create_table('scope_items',
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('item_type', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('in_scope', sa.Boolean(), nullable=False),
    sa.Column('testing_restrictions', sa.Text(), nullable=True),
    sa.Column('environment', sa.String(length=64), nullable=True),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scope_items_engagement_id'), 'scope_items', ['engagement_id'], unique=False)
    op.create_table('targets',
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=16), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('operating_system', sa.String(length=128), nullable=True),
    sa.Column('technology', sa.Text(), nullable=True),
    sa.Column('environment', sa.String(length=64), nullable=True),
    sa.Column('asset_owner', sa.String(length=128), nullable=True),
    sa.Column('auth_required', sa.Boolean(), nullable=False),
    sa.Column('creds_available', sa.Boolean(), nullable=False),
    sa.Column('in_scope', sa.Boolean(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_targets_engagement_id'), 'targets', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_targets_hostname'), 'targets', ['hostname'], unique=False)
    op.create_index(op.f('ix_targets_ip_address'), 'targets', ['ip_address'], unique=False)
    op.create_table('watch_paths',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('is_recursive', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('engagement_id', sa.String(length=36), nullable=True),
    sa.Column('file_patterns', sa.Text(), nullable=True),
    sa.Column('ignore_patterns', sa.Text(), nullable=True),
    sa.Column('last_event', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_hosts',
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('operating_system', sa.String(length=128), nullable=True),
    sa.Column('source_tool', sa.String(length=64), nullable=True),
    sa.Column('discovered_by', sa.String(length=128), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provenance_json', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engagement_id', 'hostname', 'ip_address', name='uq_asset_host')
    )
    op.create_index(op.f('ix_asset_hosts_engagement_id'), 'asset_hosts', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_asset_hosts_hostname'), 'asset_hosts', ['hostname'], unique=False)
    op.create_index(op.f('ix_asset_hosts_ip_address'), 'asset_hosts', ['ip_address'], unique=False)
    op.create_index(op.f('ix_asset_hosts_target_id'), 'asset_hosts', ['target_id'], unique=False)
    op.create_table('command_runs',
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('command_id', sa.String(length=36), nullable=True),
    sa.Column('template_name', sa.String(length=512), nullable=True),
    sa.Column('execution_profile', sa.String(length=32), nullable=False),
    sa.Column('command_preview', sa.Text(), nullable=False),
    sa.Column('command_executed', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('runner_id', sa.String(length=36), nullable=True),
    sa.Column('runner_name', sa.String(length=255), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('stdout_path', sa.String(length=1024), nullable=True),
    sa.Column('stderr_path', sa.String(length=1024), nullable=True),
    sa.Column('stdout_size', sa.Integer(), nullable=True),
    sa.Column('stderr_size', sa.Integer(), nullable=True),
    sa.Column('stdout_tail', sa.Text(), nullable=True),
    sa.Column('stderr_tail', sa.Text(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('runtime_seconds', sa.Float(), nullable=True),
    sa.Column('working_directory', sa.String(length=1024), nullable=True),
    sa.Column('output_location', sa.String(length=1024), nullable=True),
    sa.Column('explicit_confirmation', sa.Boolean(), nullable=False),
    sa.Column('scope_warning', sa.Text(), nullable=True),
    sa.Column('scope_override', sa.Boolean(), nullable=False),
    sa.Column('scope_override_reason', sa.Text(), nullable=True),
    sa.Column('stop_requested', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['command_id'], ['commands.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['runner_id'], ['runner_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_command_runs_command_id'), 'command_runs', ['command_id'], unique=False)
    op.create_index(op.f('ix_command_runs_engagement_id'), 'command_runs', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_command_runs_runner_id'), 'command_runs', ['runner_id'], unique=False)
    op.create_index(op.f('ix_command_runs_status'), 'command_runs', ['status'], unique=False)
    op.create_index(op.f('ix_command_runs_stop_requested'), 'command_runs', ['stop_requested'], unique=False)
    op.create_index(op.f('ix_command_runs_target_id'), 'command_runs', ['target_id'], unique=False)
    op.create_table('credentials',
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('secret_type', sa.String(length=64), nullable=False),
    sa.Column('encrypted_secret', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('privilege_level', sa.String(length=64), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('validation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_compromised', sa.Boolean(), nullable=False),
    sa.Column('is_reused', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credentials_engagement_id'), 'credentials', ['engagement_id'], unique=False)
    op.create_table('evidence',
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence_type', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('original_filename', sa.String(length=512), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('capture_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('captured_by', sa.String(length=128), nullable=True),
    sa.Column('source_tool', sa.String(length=64), nullable=True),
    sa.Column('command_used', sa.Text(), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('in_report', sa.Boolean(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_engagement_id'), 'evidence', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_evidence_sha256'), 'evidence', ['sha256'], unique=False)
    op.create_table('finding_duplicate_candidates',
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_finding_id', sa.String(length=36), nullable=False),
    sa.Column('fingerprint', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finding_duplicate_candidates_candidate_finding_id'), 'finding_duplicate_candidates', ['candidate_finding_id'], unique=False)
    op.create_index(op.f('ix_finding_duplicate_candidates_engagement_id'), 'finding_duplicate_candidates', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_finding_duplicate_candidates_finding_id'), 'finding_duplicate_candidates', ['finding_id'], unique=False)
    op.create_index(op.f('ix_finding_duplicate_candidates_fingerprint'), 'finding_duplicate_candidates', ['fingerprint'], unique=False)
    op.create_table('finding_targets',
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finding_targets_finding_id'), 'finding_targets', ['finding_id'], unique=False)
    op.create_index(op.f('ix_finding_targets_target_id'), 'finding_targets', ['target_id'], unique=False)
    op.create_table('links',
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('collection_id', sa.String(length=36), nullable=True),
    sa.Column('engagement_id', sa.String(length=36), nullable=True),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('finding_id', sa.String(length=36), nullable=True),
    sa.Column('auth_notes', sa.Text(), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('last_opened', sa.DateTime(timezone=True), nullable=True),
    sa.Column('open_count', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['link_collections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_links_category'), 'links', ['category'], unique=False)
    op.create_index(op.f('ix_links_engagement_id'), 'links', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_links_is_favorite'), 'links', ['is_favorite'], unique=False)
    op.create_index(op.f('ix_links_name'), 'links', ['name'], unique=False)
    op.create_table('notes',
    sa.Column('engagement_id', sa.String(length=36), nullable=True),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('finding_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('note_type', sa.String(length=64), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_engagement_id'), 'notes', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_notes_title'), 'notes', ['title'], unique=False)
    op.create_table('scan_results',
    sa.Column('scan_import_id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('finding_id', sa.String(length=36), nullable=True),
    sa.Column('result_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('data_json', sa.Text(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_import_id'], ['scan_imports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_results_scan_import_id'), 'scan_results', ['scan_import_id'], unique=False)
    op.create_table('tasks',
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('finding_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('assigned_user', sa.String(length=128), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('actual_minutes', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_engagement_id'), 'tasks', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    op.create_table('asset_services',
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=16), nullable=True),
    sa.Column('service_name', sa.String(length=128), nullable=True),
    sa.Column('banner', sa.Text(), nullable=True),
    sa.Column('technology', sa.Text(), nullable=True),
    sa.Column('source_tool', sa.String(length=64), nullable=True),
    sa.Column('discovered_by', sa.String(length=128), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provenance_json', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_id'], ['asset_hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id', 'port', 'protocol', 'service_name', name='uq_asset_service')
    )
    op.create_index(op.f('ix_asset_services_engagement_id'), 'asset_services', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_asset_services_host_id'), 'asset_services', ['host_id'], unique=False)
    op.create_table('attack_chain_steps',
    sa.Column('chain_id', sa.String(length=36), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('finding_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['attack_chains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attack_chain_steps_chain_id'), 'attack_chain_steps', ['chain_id'], unique=False)
    op.create_table('finding_evidence',
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finding_evidence_evidence_id'), 'finding_evidence', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_finding_evidence_finding_id'), 'finding_evidence', ['finding_id'], unique=False)
    op.create_table('foothold_sessions',
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('user_context', sa.String(length=255), nullable=True),
    sa.Column('privilege_level', sa.String(length=64), nullable=True),
    sa.Column('originating_finding_id', sa.String(length=36), nullable=True),
    sa.Column('credential_id', sa.String(length=36), nullable=True),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cleanup_status', sa.String(length=64), nullable=False),
    sa.Column('cleanup_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['originating_finding_id'], ['findings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foothold_sessions_engagement_id'), 'foothold_sessions', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_foothold_sessions_target_id'), 'foothold_sessions', ['target_id'], unique=False)
    op.create_table('hash_records',
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('hash_type', sa.String(length=64), nullable=True),
    sa.Column('hash_value', sa.Text(), nullable=True),
    sa.Column('source_file', sa.String(length=1024), nullable=True),
    sa.Column('is_cracked', sa.Boolean(), nullable=False),
    sa.Column('credential_id', sa.String(length=36), nullable=True),
    sa.Column('crack_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tool', sa.String(length=64), nullable=True),
    sa.Column('session_name', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hash_records_engagement_id'), 'hash_records', ['engagement_id'], unique=False)
    op.create_table('methodology_results',
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['methodology_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['methodology_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_id', 'item_id', name='uq_methodology_target_item')
    )
    op.create_index(op.f('ix_methodology_results_engagement_id'), 'methodology_results', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_methodology_results_item_id'), 'methodology_results', ['item_id'], unique=False)
    op.create_index(op.f('ix_methodology_results_profile_id'), 'methodology_results', ['profile_id'], unique=False)
    op.create_index(op.f('ix_methodology_results_status'), 'methodology_results', ['status'], unique=False)
    op.create_index(op.f('ix_methodology_results_target_id'), 'methodology_results', ['target_id'], unique=False)
    op.create_table('recon_snapshots',
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('source_run_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_run_id'], ['command_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recon_snapshots_engagement_id'), 'recon_snapshots', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_recon_snapshots_source_run_id'), 'recon_snapshots', ['source_run_id'], unique=False)
    op.create_index(op.f('ix_recon_snapshots_target_id'), 'recon_snapshots', ['target_id'], unique=False)
    op.create_table('runner_job_events',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('runner_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['command_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['runner_id'], ['runner_nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runner_job_events_event_type'), 'runner_job_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_runner_job_events_run_id'), 'runner_job_events', ['run_id'], unique=False)
    op.create_index(op.f('ix_runner_job_events_runner_id'), 'runner_job_events', ['runner_id'], unique=False)
    op.create_table('screenshot_annotations',
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('edited_evidence_id', sa.String(length=36), nullable=True),
    sa.Column('annotation_json', sa.Text(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['edited_evidence_id'], ['evidence.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screenshot_annotations_edited_evidence_id'), 'screenshot_annotations', ['edited_evidence_id'], unique=False)
    op.create_index(op.f('ix_screenshot_annotations_evidence_id'), 'screenshot_annotations', ['evidence_id'], unique=False)
    op.create_table('task_checklist_items',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_checklist_items_task_id'), 'task_checklist_items', ['task_id'], unique=False)
    op.create_table('time_entries',
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('finding_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_billable', sa.Boolean(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_entries_engagement_id'), 'time_entries', ['engagement_id'], unique=False)
    op.create_table('asset_urls',
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source_tool', sa.String(length=64), nullable=True),
    sa.Column('discovered_by', sa.String(length=128), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provenance_json', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_id'], ['asset_hosts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['asset_services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id', 'url', name='uq_asset_url')
    )
    op.create_index(op.f('ix_asset_urls_engagement_id'), 'asset_urls', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_asset_urls_host_id'), 'asset_urls', ['host_id'], unique=False)
    op.create_index(op.f('ix_asset_urls_service_id'), 'asset_urls', ['service_id'], unique=False)
    op.create_table('recon_snapshot_items',
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('normalized_key', sa.String(length=512), nullable=False),
    sa.Column('display_value', sa.Text(), nullable=False),
    sa.Column('source_tool', sa.String(length=64), nullable=True),
    sa.Column('source_job_id', sa.String(length=36), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['recon_snapshots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_job_id'], ['command_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'entity_type', 'normalized_key', name='uq_snapshot_entity')
    )
    op.create_index(op.f('ix_recon_snapshot_items_entity_type'), 'recon_snapshot_items', ['entity_type'], unique=False)
    op.create_index(op.f('ix_recon_snapshot_items_normalized_key'), 'recon_snapshot_items', ['normalized_key'], unique=False)
    op.create_index(op.f('ix_recon_snapshot_items_snapshot_id'), 'recon_snapshot_items', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_recon_snapshot_items_source_job_id'), 'recon_snapshot_items', ['source_job_id'], unique=False)
    op.create_table('asset_endpoints',
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=True),
    sa.Column('url_id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('query_params', sa.Text(), nullable=True),
    sa.Column('body_params', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('auth_requirement', sa.String(length=64), nullable=True),
    sa.Column('testing_status', sa.String(length=32), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_tool', sa.String(length=64), nullable=True),
    sa.Column('discovered_by', sa.String(length=128), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provenance_json', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_id'], ['asset_hosts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['asset_services.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['url_id'], ['asset_urls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_id', 'method', 'path', name='uq_asset_endpoint')
    )
    op.create_index(op.f('ix_asset_endpoints_engagement_id'), 'asset_endpoints', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_asset_endpoints_host_id'), 'asset_endpoints', ['host_id'], unique=False)
    op.create_index(op.f('ix_asset_endpoints_method'), 'asset_endpoints', ['method'], unique=False)
    op.create_index(op.f('ix_asset_endpoints_service_id'), 'asset_endpoints', ['service_id'], unique=False)
    op.create_index(op.f('ix_asset_endpoints_target_id'), 'asset_endpoints', ['target_id'], unique=False)
    op.create_index(op.f('ix_asset_endpoints_testing_status'), 'asset_endpoints', ['testing_status'], unique=False)
    op.create_index(op.f('ix_asset_endpoints_url_id'), 'asset_endpoints', ['url_id'], unique=False)
    op.create_table('credential_usages',
    sa.Column('credential_id', sa.String(length=36), nullable=False),
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('host_id', sa.String(length=36), nullable=True),
    sa.Column('service_id', sa.String(length=36), nullable=True),
    sa.Column('endpoint_id', sa.String(length=36), nullable=True),
    sa.Column('usage_context', sa.Text(), nullable=True),
    sa.Column('validation_state', sa.String(length=32), nullable=False),
    sa.Column('last_validation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['endpoint_id'], ['asset_endpoints.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_id'], ['asset_hosts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['asset_services.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credential_usages_credential_id'), 'credential_usages', ['credential_id'], unique=False)
    op.create_index(op.f('ix_credential_usages_engagement_id'), 'credential_usages', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_credential_usages_target_id'), 'credential_usages', ['target_id'], unique=False)
    op.create_table('endpoint_parameters',
    sa.Column('endpoint_id', sa.String(length=36), nullable=False),
    sa.Column('location', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sample_value', sa.Text(), nullable=True),
    sa.Column('source_tool', sa.String(length=64), nullable=True),
    sa.Column('discovered_by', sa.String(length=128), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['asset_endpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint_id', 'location', 'name', name='uq_endpoint_parameter')
    )
    op.create_index(op.f('ix_endpoint_parameters_endpoint_id'), 'endpoint_parameters', ['endpoint_id'], unique=False)
    op.create_table('http_messages',
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('endpoint_id', sa.String(length=36), nullable=True),
    sa.Column('method', sa.String(length=16), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('request_raw', sa.Text(), nullable=True),
    sa.Column('response_raw', sa.Text(), nullable=True),
    sa.Column('request_pretty', sa.Text(), nullable=True),
    sa.Column('response_pretty', sa.Text(), nullable=True),
    sa.Column('source_tool', sa.String(length=64), nullable=True),
    sa.Column('is_redacted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['asset_endpoints.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_http_messages_endpoint_id'), 'http_messages', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_http_messages_engagement_id'), 'http_messages', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_http_messages_target_id'), 'http_messages', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_http_messages_target_id'), table_name='http_messages')
    op.drop_index(op.f('ix_http_messages_engagement_id'), table_name='http_messages')
    op.drop_index(op.f('ix_http_messages_endpoint_id'), table_name='http_messages')
    op.drop_table('http_messages')
    op.drop_index(op.f('ix_endpoint_parameters_endpoint_id'), table_name='endpoint_parameters')
    op.drop_table('endpoint_parameters')
    op.drop_index(op.f('ix_credential_usages_target_id'), table_name='credential_usages')
    op.drop_index(op.f('ix_credential_usages_engagement_id'), table_name='credential_usages')
    op.drop_index(op.f('ix_credential_usages_credential_id'), table_name='credential_usages')
    op.drop_table('credential_usages')
    op.drop_index(op.f('ix_asset_endpoints_url_id'), table_name='asset_endpoints')
    op.drop_index(op.f('ix_asset_endpoints_testing_status'), table_name='asset_endpoints')
    op.drop_index(op.f('ix_asset_endpoints_target_id'), table_name='asset_endpoints')
    op.drop_index(op.f('ix_asset_endpoints_service_id'), table_name='asset_endpoints')
    op.drop_index(op.f('ix_asset_endpoints_method'), table_name='asset_endpoints')
    op.drop_index(op.f('ix_asset_endpoints_host_id'), table_name='asset_endpoints')
    op.drop_index(op.f('ix_asset_endpoints_engagement_id'), table_name='asset_endpoints')
    op.drop_table('asset_endpoints')
    op.drop_index(op.f('ix_recon_snapshot_items_source_job_id'), table_name='recon_snapshot_items')
    op.drop_index(op.f('ix_recon_snapshot_items_snapshot_id'), table_name='recon_snapshot_items')
    op.drop_index(op.f('ix_recon_snapshot_items_normalized_key'), table_name='recon_snapshot_items')
    op.drop_index(op.f('ix_recon_snapshot_items_entity_type'), table_name='recon_snapshot_items')
    op.drop_table('recon_snapshot_items')
    op.drop_index(op.f('ix_asset_urls_service_id'), table_name='asset_urls')
    op.drop_index(op.f('ix_asset_urls_host_id'), table_name='asset_urls')
    op.drop_index(op.f('ix_asset_urls_engagement_id'), table_name='asset_urls')
    op.drop_table('asset_urls')
    op.drop_index(op.f('ix_time_entries_engagement_id'), table_name='time_entries')
    op.drop_table('time_entries')
    op.drop_index(op.f('ix_task_checklist_items_task_id'), table_name='task_checklist_items')
    op.drop_table('task_checklist_items')
    op.drop_index(op.f('ix_screenshot_annotations_evidence_id'), table_name='screenshot_annotations')
    op.drop_index(op.f('ix_screenshot_annotations_edited_evidence_id'), table_name='screenshot_annotations')
    op.drop_table('screenshot_annotations')
    op.drop_index(op.f('ix_runner_job_events_runner_id'), table_name='runner_job_events')
    op.drop_index(op.f('ix_runner_job_events_run_id'), table_name='runner_job_events')
    op.drop_index(op.f('ix_runner_job_events_event_type'), table_name='runner_job_events')
    op.drop_table('runner_job_events')
    op.drop_index(op.f('ix_recon_snapshots_target_id'), table_name='recon_snapshots')
    op.drop_index(op.f('ix_recon_snapshots_source_run_id'), table_name='recon_snapshots')
    op.drop_index(op.f('ix_recon_snapshots_engagement_id'), table_name='recon_snapshots')
    op.drop_table('recon_snapshots')
    op.drop_index(op.f('ix_methodology_results_target_id'), table_name='methodology_results')
    op.drop_index(op.f('ix_methodology_results_status'), table_name='methodology_results')
    op.drop_index(op.f('ix_methodology_results_profile_id'), table_name='methodology_results')
    op.drop_index(op.f('ix_methodology_results_item_id'), table_name='methodology_results')
    op.drop_index(op.f('ix_methodology_results_engagement_id'), table_name='methodology_results')
    op.drop_table('methodology_results')
    op.drop_index(op.f('ix_hash_records_engagement_id'), table_name='hash_records')
    op.drop_table('hash_records')
    op.drop_index(op.f('ix_foothold_sessions_target_id'), table_name='foothold_sessions')
    op.drop_index(op.f('ix_foothold_sessions_engagement_id'), table_name='foothold_sessions')
    op.drop_table('foothold_sessions')
    op.drop_index(op.f('ix_finding_evidence_finding_id'), table_name='finding_evidence')
    op.drop_index(op.f('ix_finding_evidence_evidence_id'), table_name='finding_evidence')
    op.drop_table('finding_evidence')
    op.drop_index(op.f('ix_attack_chain_steps_chain_id'), table_name='attack_chain_steps')
    op.drop_table('attack_chain_steps')
    op.drop_index(op.f('ix_asset_services_host_id'), table_name='asset_services')
    op.drop_index(op.f('ix_asset_services_engagement_id'), table_name='asset_services')
    op.drop_table('asset_services')
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_engagement_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_scan_results_scan_import_id'), table_name='scan_results')
    op.drop_table('scan_results')
    op.drop_index(op.f('ix_notes_title'), table_name='notes')
    op.drop_index(op.f('ix_notes_engagement_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_links_name'), table_name='links')
    op.drop_index(op.f('ix_links_is_favorite'), table_name='links')
    op.drop_index(op.f('ix_links_engagement_id'), table_name='links')
    op.drop_index(op.f('ix_links_category'), table_name='links')
    op.drop_table('links')
    op.drop_index(op.f('ix_finding_targets_target_id'), table_name='finding_targets')
    op.drop_index(op.f('ix_finding_targets_finding_id'), table_name='finding_targets')
    op.drop_table('finding_targets')
    op.drop_index(op.f('ix_finding_duplicate_candidates_fingerprint'), table_name='finding_duplicate_candidates')
    op.drop_index(op.f('ix_finding_duplicate_candidates_finding_id'), table_name='finding_duplicate_candidates')
    op.drop_index(op.f('ix_finding_duplicate_candidates_engagement_id'), table_name='finding_duplicate_candidates')
    op.drop_index(op.f('ix_finding_duplicate_candidates_candidate_finding_id'), table_name='finding_duplicate_candidates')
    op.drop_table('finding_duplicate_candidates')
    op.drop_index(op.f('ix_evidence_sha256'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_engagement_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_credentials_engagement_id'), table_name='credentials')
    op.drop_table('credentials')
    op.drop_index(op.f('ix_command_runs_target_id'), table_name='command_runs')
    op.drop_index(op.f('ix_command_runs_stop_requested'), table_name='command_runs')
    op.drop_index(op.f('ix_command_runs_status'), table_name='command_runs')
    op.drop_index(op.f('ix_command_runs_runner_id'), table_name='command_runs')
    op.drop_index(op.f('ix_command_runs_engagement_id'), table_name='command_runs')
    op.drop_index(op.f('ix_command_runs_command_id'), table_name='command_runs')
    op.drop_table('command_runs')
    op.drop_index(op.f('ix_asset_hosts_target_id'), table_name='asset_hosts')
    op.drop_index(op.f('ix_asset_hosts_ip_address'), table_name='asset_hosts')
    op.drop_index(op.f('ix_asset_hosts_hostname'), table_name='asset_hosts')
    op.drop_index(op.f('ix_asset_hosts_engagement_id'), table_name='asset_hosts')
    op.drop_table('asset_hosts')
    op.drop_table('watch_paths')
    op.drop_index(op.f('ix_targets_ip_address'), table_name='targets')
    op.drop_index(op.f('ix_targets_hostname'), table_name='targets')
    op.drop_index(op.f('ix_targets_engagement_id'), table_name='targets')
    op.drop_table('targets')
    op.drop_index(op.f('ix_scope_items_engagement_id'), table_name='scope_items')
    op.drop_table('scope_items')
    op.drop_index(op.f('ix_scan_imports_engagement_id'), table_name='scan_imports')
    op.drop_table('scan_imports')
    op.drop_index(op.f('ix_reports_engagement_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_table('link_collections')
    op.drop_index(op.f('ix_findings_title'), table_name='findings')
    op.drop_index(op.f('ix_findings_status'), table_name='findings')
    op.drop_index(op.f('ix_findings_severity'), table_name='findings')
    op.drop_index(op.f('ix_findings_engagement_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_engagement_members_engagement_id'), table_name='engagement_members')
    op.drop_table('engagement_members')
    op.drop_index(op.f('ix_engagement_checklist_items_engagement_id'), table_name='engagement_checklist_items')
    op.drop_index(op.f('ix_engagement_checklist_items_checklist_type'), table_name='engagement_checklist_items')
    op.drop_table('engagement_checklist_items')
    op.drop_index(op.f('ix_attack_relationships_engagement_id'), table_name='attack_relationships')
    op.drop_table('attack_relationships')
    op.drop_index(op.f('ix_attack_chains_engagement_id'), table_name='attack_chains')
    op.drop_table('attack_chains')
    op.drop_index(op.f('ix_activity_events_event_type'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_engagement_id'), table_name='activity_events')
    op.drop_table('activity_events')
    op.drop_index(op.f('ix_methodology_items_profile_id'), table_name='methodology_items')
    op.drop_table('methodology_items')
    op.drop_index(op.f('ix_entity_tags_entity_type'), table_name='entity_tags')
    op.drop_index(op.f('ix_entity_tags_entity_id'), table_name='entity_tags')
    op.drop_table('entity_tags')
    op.drop_index(op.f('ix_engagements_status'), table_name='engagements')
    op.drop_index(op.f('ix_engagements_name'), table_name='engagements')
    op.drop_index(op.f('ix_engagements_client_id'), table_name='engagements')
    op.drop_table('engagements')
    op.drop_index(op.f('ix_client_contacts_client_id'), table_name='client_contacts')
    op.drop_table('client_contacts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_runner_nodes_name'), table_name='runner_nodes')
    op.drop_table('runner_nodes')
    op.drop_index(op.f('ix_payloads_name'), table_name='payloads')
    op.drop_index(op.f('ix_payloads_category'), table_name='payloads')
    op.drop_table('payloads')
    op.drop_index(op.f('ix_methodology_profiles_name'), table_name='methodology_profiles')
    op.drop_table('methodology_profiles')
    op.drop_index(op.f('ix_finding_templates_title'), table_name='finding_templates')
    op.drop_table('finding_templates')
    op.drop_index(op.f('ix_commands_name'), table_name='commands')
    op.drop_index(op.f('ix_commands_category'), table_name='commands')
    op.drop_table('commands')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_table('clients')
    op.drop_table('backups')
    op.drop_index(op.f('ix_application_settings_key'), table_name='application_settings')
    op.drop_table('application_settings')
    # ### end Alembic commands ###
