"""Main API router."""
from __future__ import annotations

from fastapi import APIRouter, Depends

from backend.app.api import (
    activity,
    auth,
    backups,
    clients,
    commands,
    credentials,
    engagements,
    evidence,
    findings,
    health,
    links,
    notes,
    operator,
    payloads,
    reports,
    runners,
    scans,
    scope,
    search,
    settings,
    targets,
    tasks,
    time_entries,
    watch_paths,
)
from backend.app.auth import require_authenticated_user, require_staff_user

api_router = APIRouter()

api_router.include_router(auth.router, prefix="/auth", tags=["auth"])
api_router.include_router(health.router, tags=["health"])
api_router.include_router(
    clients.router,
    prefix="/clients",
    tags=["clients"],
    dependencies=[Depends(require_staff_user)],
)
api_router.include_router(
    engagements.router,
    prefix="/engagements",
    tags=["engagements"],
    dependencies=[Depends(require_staff_user)],
)
api_router.include_router(
    scope.router,
    prefix="/scope",
    tags=["scope"],
    dependencies=[Depends(require_staff_user)],
)
api_router.include_router(
    targets.router,
    prefix="/targets",
    tags=["targets"],
    dependencies=[Depends(require_staff_user)],
)
api_router.include_router(
    findings.router,
    prefix="/findings",
    tags=["findings"],
    dependencies=[Depends(require_authenticated_user)],
)
api_router.include_router(
    evidence.router,
    prefix="/evidence",
    tags=["evidence"],
    dependencies=[Depends(require_staff_user)],
)
api_router.include_router(
    credentials.router,
    prefix="/credentials",
    tags=["credentials"],
    dependencies=[Depends(require_staff_user)],
)
api_router.include_router(
    tasks.router,
    prefix="/tasks",
    tags=["tasks"],
    dependencies=[Depends(require_staff_user)],
)
api_router.include_router(
    notes.router,
    prefix="/notes",
    tags=["notes"],
    dependencies=[Depends(require_staff_user)],
)
api_router.include_router(
    operator.router,
    prefix="/operator",
    tags=["operator"],
    dependencies=[Depends(require_staff_user)],
)
api_router.include_router(
    links.router,
    prefix="/links",
    tags=["links"],
    dependencies=[Depends(require_staff_user)],
)
api_router.include_router(
    commands.router,
    prefix="/commands",
    tags=["commands"],
    dependencies=[Depends(require_staff_user)],
)
api_router.include_router(
    payloads.router,
    prefix="/payloads",
    tags=["payloads"],
    dependencies=[Depends(require_staff_user)],
)
api_router.include_router(
    scans.router,
    prefix="/scans",
    tags=["scans"],
    dependencies=[Depends(require_staff_user)],
)
api_router.include_router(
    reports.router,
    prefix="/reports",
    tags=["reports"],
    dependencies=[Depends(require_staff_user)],
)
api_router.include_router(runners.router, prefix="/runners", tags=["runners"])
api_router.include_router(
    activity.router,
    prefix="/activity",
    tags=["activity"],
    dependencies=[Depends(require_staff_user)],
)
api_router.include_router(
    time_entries.router,
    prefix="/time-entries",
    tags=["time-entries"],
    dependencies=[Depends(require_staff_user)],
)
api_router.include_router(
    backups.router,
    prefix="/backups",
    tags=["backups"],
    dependencies=[Depends(require_staff_user)],
)
api_router.include_router(
    watch_paths.router,
    prefix="/watch-paths",
    tags=["watch-paths"],
    dependencies=[Depends(require_staff_user)],
)
api_router.include_router(
    settings.router,
    prefix="/settings",
    tags=["settings"],
    dependencies=[Depends(require_staff_user)],
)
api_router.include_router(
    search.router,
    prefix="/search",
    tags=["search"],
    dependencies=[Depends(require_staff_user)],
)
